threshold_buy = 0.6
threshold_sell = -0.67
method = 'adadelta'

learning_rate = 0.1
momentum = 0.9
decay = 0.16
stoploss_enabled = true
stoploss_threshold = 0.85
hodl_threshold = 1
price_buffer_len = 700
min_predictions = 1000
